services:
  - type: web
    name: servidor-video
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: sleep 10 && gunicorn app:app --bind 0.0.0.0:$PORT
    environment:
      pythonVersion: 3.10.13